### PR TITLE
Build system improvements

### PR DESCRIPTION
**Pull request by maksymko**
This change is not ready for prime time yet, just want to check if you'd be interested in taking some thing like this and if there are any high-level concerns you have.

Also, are you still interested in maintaining this fork?

### CODE REVIEW

**Comment by l29ah** [comment]
Looks good to me. I'm not proficient enough in autotools to assess the quality though.
Yeah, i rely on libmpsse working in my projects.

**Comment by maksymko** [comment]
@l29ah which platform are you using this on? Linux/OSX/Windows?

**Comment by l29ah** [comment]
I'm on GNU/Linux, it should work everywhere else, though i haven't tested it.

**Comment by maksymko** [comment]
@l29ah This is good to go now.

I've tested this on GNU/Linux, with the included examples. There should be no functional changes.

**Comment by l29ah** [comment]
I don't like the fact that it won't let me build the library w/o pulling SWIG for the python bindings, can it be helped? There still are systems that work without the bliss of a package manager and pkg-config (like Windows).

**Comment by maksymko** [comment]
To clarify: you still want to be able to build the library without Python bindings? That certainly can be addressed, I was just under the impression that the Python bindings is the main feature of this library.

If you want to build Python bindings without SWIG though... I have no idea how to do that. Right now the build still uses SWIG.

**Comment by l29ah** [comment]
Yeah. I never used them in fact.

**Comment by maksymko** [comment]
OK, put `--disable-python` feature back.

**Comment by l29ah** [comment]
Pulled, thanks!

**Pull request closed without merging**
