### PR TITLE
Fix config.h include for libftdi defines

### LINKED ISSUE #13: [OSX] libftdi include <ftdi.h> compilation error
Cannot compile library on osx due to the library not using the correct libftdi1 include path. I believe this is due to the generated `config.h` file being included after the `mpsse.h` include here: https://github.com/l29ah/libmpsse/blob/master/src/mpsse.c#L15

Would it make sense to instead include the `config.h` defines within `mpsse.h` since it is used amongst many parts of this library?

```
➜  src git:(master) make
cp -f support.c pyswig_support.c
cp -f mpsse.c pyswig_mpsse.c
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in .
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.     -Wall -Wextra -fPIC -fno-strict-aliasing -g -O2 -g -O2 -g -O2 -MT mpsse.lo -MD -MP -MF .deps/mpsse.Tpo -c -o mpsse.lo mpsse.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -Wall -Wextra -fPIC -fno-strict-aliasing -g -O2 -g -O2 -g -O2 -MT mpsse.lo -MD -MP -MF .deps/mpsse.Tpo -c mpsse.c  -fno-common -DPIC -o .libs/mpsse.o
In file included from mpsse.c:13:
./mpsse.h:9:10: fatal error: 'ftdi.h' file not found
#include <ftdi.h>
         ^~~~~~~~
1 error generated.
make[2]: *** [mpsse.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by derekolson**
Move config.h include to mpsse.h so that the defines in the config file can be referenced

fixes #13

### CODE REVIEW

**Comment by l29ah** [comment]
The solution is invalid since config.h only exists during the library build process and doesn't get installed into the system, unlike mpsse.h.

**Comment by derekolson** [comment]
Yeah I realized that after the fact... does that mean including the `config.h` before every file that requires `mpsse.h`?

**Comment by derekolson** [comment]
The only other solution I can think of would be adding a define to the Makefile for `HAVE_LIBFTDI1` for configurations that have libftdi1

**Comment by l29ah** [comment]
Merged, thanks.

**Comment by l29ah** [comment]
Out of curiosity, what are your `config.h` contents?

**Comment by derekolson** [comment]
```
/* config.h.  Generated from config.h.in by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <float.h> header file. */
#define HAVE_FLOAT_H 1

/* Define to 1 if you have the `floor' function. */
#define HAVE_FLOOR 1

/* Define to 1 if you have the <ftdi.h> header file. */
/* #undef HAVE_FTDI_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `ftdi' library (-lftdi). */
/* #undef HAVE_LIBFTDI */

/* Define to 1 if you have the `ftdi1' library (-lftdi1). */
#define HAVE_LIBFTDI1 1

/* Define to 1 if you have the <libftdi1/ftdi.h> header file. */
#define HAVE_LIBFTDI1_FTDI_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if your system has a GNU libc compatible `malloc' function, and
   to 0 otherwise. */
#define HAVE_MALLOC 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `memset' function. */
#define HAVE_MEMSET 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the `strchr' function. */
#define HAVE_STRCHR 1

/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if the system has the type `_Bool'. */
#define HAVE__BOOL 1

/* Define to the sub-directory where libtool stores uninstalled libraries. */
#define LT_OBJDIR ".libs/"

/* Name of package */
#define PACKAGE "libmpsse"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://github.com/l29ah/libmpsse/issues"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libmpsse"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libmpsse 1.3.2"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libmpsse"

/* Define to the home page for this package. */
#define PACKAGE_URL ""

/* Define to the version of this package. */
#define PACKAGE_VERSION "1.3.2"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "1.3.2"

/* Define for Solaris 2.5.1 so the uint32_t typedef from <sys/synch.h>,
   <pthread.h>, or <semaphore.h> is not used. If the typedef were allowed, the
   #define below would cause a syntax error. */
/* #undef _UINT32_T */

/* Define for Solaris 2.5.1 so the uint8_t typedef from <sys/synch.h>,
   <pthread.h>, or <semaphore.h> is not used. If the typedef were allowed, the
   #define below would cause a syntax error. */
/* #undef _UINT8_T */

/* Define to rpl_malloc if the replacement function should be used. */
/* #undef malloc */

/* Define to `unsigned int' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to the type of an unsigned integer type of width exactly 16 bits if
   such a type exists and the standard includes do not define it. */
/* #undef uint16_t */

/* Define to the type of an unsigned integer type of width exactly 32 bits if
   such a type exists and the standard includes do not define it. */
/* #undef uint32_t */

/* Define to the type of an unsigned integer type of width exactly 8 bits if
   such a type exists and the standard includes do not define it. */
/* #undef uint8_t */
```

**Comment by derekolson** [comment]
I'm not too versed at the autoconfigure stuff, but I wonder if these defines would be better off placed into a generated mpsse.h header file (through a mpsse.h.in), instead of needing to create a separate config to include?

**Comment by l29ah** [comment]
I have little clues re autotools functionality as well, maybe it makes more sense to @maksymko

**Comment by maksymko** [comment]
Yep, sounds like a bug. I know realize that the only reason it worked for me is because I have *both* versions if the libftdi library installed.

`mpsse.h` should not be doing this conditional include, i.e. having this dependency on a build time configuration.

One option would be, as @derekolson suggested, to autogenerate `mpsse.h`, using [ax_prefix_config_h](https://www.gnu.org/software/autoconf-archive/ax_prefix_config_h.html). This is an "easy" solution.

The "correct" solution though, IMHO, would be to fully privatize libftdi dependency, so that it only exists at runtime. To do that you would need to redefine a few things in `mpsse.h` (like `INTERFACE_{A,B,C,D,ANY}`) and change `struct ftdi_context ftdi` to `struct ftdi_context* ftdi`. This is quite elaborate, but also not ideal, because you still need to know which libftdi library to link against when building your application.

Maybe just ditch libftdi and depend on libftdi1 only? This would probably be the most clean solution.

**Comment by maksymko** [comment]
Of course, you can also simply generate mpsse.h at build time with this particular include picked at generation time. Also looks pretty clean.

Let me know what your thoughts are. You can also assign the bug to me -- if the solution we agree on is not too elaborate, I'd be happy to implement it.

**Pull request closed without merging**
